# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190213_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='fn',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
